version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: telemed_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=parola
      - POSTGRES_DB=telemedicina_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata: